name: der_3
description: "A new Flutter project."

publish_to:
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0
  path: ^1.8.2

  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/Movie.png
    - lib/assets/images/tv.png


